CREATE DATABASE canil2;

USE canil2;

CREATE TABLE USUARIO(
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    CNPJ VARCHAR(18) NOT NULL UNIQUE,
    TELEFONE VARCHAR(15) NOT NULL,
    CELULAR VARCHAR(15) NOT NULL,
    ORGANIZACAO VARCHAR(50) NOT NULL,
    REDESOCIAL VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    SENHA VARCHAR(50) NOT NULL
);

CREATE TABLE ANIMAL(
    IDANIMAL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    GENERO CHAR(1),
    PORTE VARCHAR(10) NOT NULL,
    IDADE INT NOT NULL,
    ESPECIE VARCHAR(10) NOT NULL,
    RACA VARCHAR(50) NOT NULL,
    INFORMACOES VARCHAR(100) NOT NULL,
    IMAGEM MEDIUMBLOB NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    NUMERO INT,
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE INTERESSE(
    IDINTERESSE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IDUSUARIO INT NOT NULL,
    IDANIMAL INT NOT NULL,
    DATAINTERESSE DATETIME NOT NULL,
    CONFIRMADO BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    FOREIGN KEY (IDANIMAL) REFERENCES ANIMAL(IDANIMAL)
);

SELECT 
    A.IDANIMAL,
    A.NOME AS NOME_ANIMAL,
    A.GENERO,
    A.PORTE,
    A.IDADE,
    A.ESPECIE,
    A.RACA,
    A.INFORMACOES,
    A.IMAGEM,
    A.CIDADE,
    A.ESTADO,
    A.ENDERECO,
    A.BAIRRO,
    A.NUMERO,
    U.NOME AS NOME_DOADOR,
    U.ORGANIZACAO AS ORGANIZACAO_DOADOR
FROM 
    ANIMAL A
INNER JOIN 
    USUARIO U ON A.IDUSUARIO = U.IDUSUARIO;

SELECT 
    I.IDINTERESSE,
    I.DATAINTERESSE,
    I.CONFIRMADO,
    U.NOME AS NOME_USUARIO,
    U.EMAIL AS EMAIL_USUARIO,
    U.TELEFONE,
    A.NOME AS NOME_ANIMAL,
    A.ESPECIE,
    A.RACA,
    A.IDADE,
    UD.NOME AS NOME_DOADOR,
    UD.ORGANIZACAO AS ORGANIZACAO_DOADOR
FROM 
    INTERESSE I
INNER JOIN 
    USUARIO U ON I.IDUSUARIO = U.IDUSUARIO
INNER JOIN 
    ANIMAL A ON I.IDANIMAL = A.IDANIMAL
INNER JOIN 
    USUARIO UD ON A.IDUSUARIO = UD.IDUSUARIO
WHERE
    U.ORGANIZACAO IS NULL; -- Garantir que o interessado seja um usuário individual

SELECT 
    A.IDANIMAL,
    A.NOME AS NOME_ANIMAL,
    A.GENERO,
    A.PORTE,
    A.IDADE,
    A.ESPECIE,
    A.RACA,
    A.INFORMACOES,
    A.IMAGEM,
    A.CIDADE,
    A.ESTADO,
    A.ENDERECO,
    A.BAIRRO,
    A.NUMERO,
    U.NOME AS NOME_DOADOR,
    U.ORGANIZACAO AS ORGANIZACAO_DOADOR
FROM 
    ANIMAL A
INNER JOIN 
    USUARIO U ON A.IDUSUARIO = U.IDUSUARIO
WHERE
    U.ORGANIZACAO IS NOT NULL; -- Garantir que seja uma organização

